<?php
$tag->section('id="contato"');
    $tag->div('class="container"');
        $tag->div('class="row text-center header animate-in" data-anim-type="fade-in-up"');
            $tag->div('class="col-xs-12 col-sm-12 col-md-12 col-lg-12"');
                $tag->h3();
                    $tag->printer(CONTACT);
                $tag->h3;
                $tag->hr();
            $tag->div;
        $tag->div;
        $tag->div('class="row animate-in" data-anim-type="fade-in-up"');
            $tag->div('class="col-xs-12 col-sm-4 col-md-4 col-lg-4"');
                $tag->div('class="contact-wrapper"');
                    $tag->h3();
                       $tag->printer(SOCIAL_TITLE);
                    $tag->h3;
                    $tag->p();
                        $tag->printer(SOCIAL_MSG);
                    $tag->p;
                    $tag->div('class="social-below"');
                        $tag->a('href="' . FACEBOOK_URL . '" target="_blank" class="btn button-custom btn-custom-two"');
                            $tag->printer(FACEBOOK_PAGE);
                        $tag->a;
                        $tag->a('href="' . TWITTER_URL . '" target="_blank" class="btn button-custom btn-custom-two"');
                            $tag->printer(TWITTER_PAGE);
                        $tag->a;
                        $tag->a('href="' . GOOGLE_PLUS_URL . '" target="_blank" class="btn button-custom btn-custom-two"');
                            $tag->printer(GOOGLE_PAGE);
                        $tag->a;
                    $tag->div;
                $tag->div;
            $tag->div;

            $tag->div('class="col-xs-12 col-sm-4 col-md-4 col-lg-4"');
                $tag->div('class="contact-wrapper"');
                    $tag->h3();
                        $tag->printer(CONTACT_TITLE);
                    $tag->h3;
                    $tag->h4();
                        $tag->strong();
                            $tag->printer(CONTACT_EMAIL_LABEL);
                        $tag->strong;
                        $tag->printer(CONTACT_EMAIL_CONTENT);
                    $tag->h4;
                    $tag->h4();
                        $tag->strong();
                            $tag->printer(CONTACT_CALL_LABEL);
                        $tag->strong;
                        $tag->printer(CONTACT_CALL_CONTENT);
                    $tag->h4;
                    $tag->h4();
                        $tag->strong();
                            $tag->printer(CONTACT_SKYPE_LABEL);
                        $tag->strong;
                        $tag->printer(CONTACT_SKYPE_CONTENT);
                    $tag->h4;
                $tag->div;
            $tag->div;
            $tag->div('class="col-xs-12 col-sm-4 col-md-4 col-lg-4"');
                $tag->div('class="contact-wrapper"');
                    $tag->h3();
                        $tag->printer(ADDRESS);
                    $tag->h3;
                    $tag->h4();
                        $tag->printer(ADDRESS_CONTENT); 
                    $tag->h4;
                    $tag->h4();
                        $tag->printer(ADDRESS_COUNTRY_CONTENT);
                    $tag->h4;
                    $tag->div('class="footer-div"');
                        $tag->printer(COPYRIGHT);
                        $tag->a('href="' . DESIGM_BOOTSTRAP . '" target="_blank"');
                            $tag->printer(TEMPLATE_NAME);
                        $tag->a;
                    $tag->div;
                $tag->div;
            $tag->div;
        $tag->div;
    $tag->div;
$tag->section;