<?php

$helper->label_sheet(SHEET_TYPE_LABELS, SHEET_TYPE_ID);
$helper->label_sheet(SHEET_SUBTYPE_LABELS, SHEET_SUBTYPE_ID);
$helper->label_sheet(SHEET_SIZE_LABELS, SHEET_SIZE_ID);
$helper->label_sheet(SHEET_CHALLENGE_LEVEL_LABEL, SHEET_CHALLENGE_LEVEL_ID);
$helper->label_sheet(SHEET_SPACE_LABELS, SHEET_SPACE_ID);
$helper->label_sheet(SHEET_REACH_LABELS, SHEET_REACH_ID);
$helper->label_sheet(SHEET_HEIGHT_LABELS, SHEET_DIMENSION_ID);
$helper->label_sheet(SHEET_WEIGHT_LABELS, SHEET_WEIGHT_ID);

$helper->label_sheet(SHEET_FORCE_LABELS, SHEET_FORCE_ID);
$helper->label_sheet(SHEET_DEXTERITY_LABELS, SHEET_DEXTERITY_ID);
$helper->label_sheet(SHEET_CONSTITUTION_LABELS, SHEET_CONSTITUTION_ID);
$helper->label_sheet(SHEET_INTELLIGENCE_LABELS, SHEET_INTELLIGENCE_ID);
$helper->label_sheet(SHEET_WISDOM_LABELS, SHEET_WISDOM_ID);
$helper->label_sheet(SHEET_CHARISMA_LABELS, SHEET_CHARISMA_ID);

$helper->label_sheet(SHEET_HEALTH_POINTS_LABELS, SHEET_HEALTH_POINTS_MONSTER_ID);
$helper->label_sheet(SHEET_CLASS_ARMOR_LABELS, SHEET_CLASS_ARMOR_ID);
$helper->label_sheet(SHEET_WILL_LABELS, SHEET_WILL_ID);	
$helper->label_sheet(SHEET_INITIATIVE_LABELS, SHEET_INITIATIVE_ID);	
$helper->label_sheet(SHEET_BONUS_ATTACK_LABELS, SHEET_BONUS_ATTACK_ID);	
$helper->label_sheet(SHEET_WEALTH_LABELS, SHEET_WEALTH_ID);	


$helper->label_sheet(SHEET_TEST_RESISTENCE_LABELS);
