<?php

// config paths
const CONFIG_TXT_PATH = URL_BASE_INTERNAL . 'config/txt/';
const ADVENTURES_TXT_PATH = CONFIG_TXT_PATH . 'aventuras/';
const MEDIVEL_ADVENTURES_TXT_PATH = ADVENTURES_TXT_PATH . 'medieval/';
const STAR_WAR_ADVENTURES_TXT_PATH = ADVENTURES_TXT_PATH . 'starwars/';
const APOCALIPSE_ADVENTURES_TXT_PATH = ADVENTURES_TXT_PATH . 'apocaliptica/';

const TXT_PATH = 'config/txt/';
const PART_1_TXT_PATH = 'part-1';
const PART_2_TXT_PATH = 'part-2';
const ANTAGONIST_TXT_PATH = 'antagonista/';
const SUPPORTING_TXT_PATH = 'coadjuvantes/';
const COMPLICATION_TXT_PATH = 'complicacao/';
const LOCALITY_TXT_PATH = 'localidade/';
const OBJECTIVE_TXT_PATH = 'objetivos/';
const REWARDS_TXT_PATH = 'recompensas/';

const MEDIVEL_ANTGONIST_TXT_PATH = MEDIVEL_ADVENTURES_TXT_PATH . ANTAGONIST_TXT_PATH;
const MEDIVEL_SUPPORTING_TXT_PATH = MEDIVEL_ADVENTURES_TXT_PATH . SUPPORTING_TXT_PATH;
const MEDIVEL_COMPLICATION_TXT_PATH = MEDIVEL_ADVENTURES_TXT_PATH . COMPLICATION_TXT_PATH;
const MEDIVEL_LOCALITY_TXT_PATH = MEDIVEL_ADVENTURES_TXT_PATH . LOCALITY_TXT_PATH;
const MEDIVEL_OBJECTIVE_TXT_PATH = MEDIVEL_ADVENTURES_TXT_PATH . OBJECTIVE_TXT_PATH;
const MEDIVEL_REWARDS_TXT_PATH = MEDIVEL_ADVENTURES_TXT_PATH . REWARDS_TXT_PATH;

const APOCALIPSE_ANTGONIST_TXT_PATH = APOCALIPSE_ADVENTURES_TXT_PATH . ANTAGONIST_TXT_PATH;
const APOCALIPSE_SUPPORTING_TXT_PATH = APOCALIPSE_ADVENTURES_TXT_PATH . SUPPORTING_TXT_PATH;
const APOCALIPSE_COMPLICATION_TXT_PATH = APOCALIPSE_ADVENTURES_TXT_PATH . COMPLICATION_TXT_PATH;
const APOCALIPSE_LOCALITY_TXT_PATH = APOCALIPSE_ADVENTURES_TXT_PATH . LOCALITY_TXT_PATH;
const APOCALIPSE_OBJECTIVE_TXT_PATH = APOCALIPSE_ADVENTURES_TXT_PATH . OBJECTIVE_TXT_PATH;
const APOCALIPSE_REWARDS_TXT_PATH = APOCALIPSE_ADVENTURES_TXT_PATH . REWARDS_TXT_PATH;

const STAR_WAR_ANTGONIST_TXT_PATH = STAR_WAR_ADVENTURES_TXT_PATH;
const STAR_WAR_SUPPORTING_TXT_PATH = STAR_WAR_ADVENTURES_TXT_PATH;
const STAR_WAR_COMPLICATION_TXT_PATH = STAR_WAR_ADVENTURES_TXT_PATH;
const STAR_WAR_LOCALITY_TXT_PATH = STAR_WAR_ADVENTURES_TXT_PATH;
const STAR_WAR_OBJECTIVE_TXT_PATH = STAR_WAR_ADVENTURES_TXT_PATH;
const STAR_WAR_REWARDS_TXT_PATH = STAR_WAR_ADVENTURES_TXT_PATH;