<?php

class Sistemasrpg_Helper{
	
	function __construct(){
		$this->language = new Locale_Lib;
		$this->nomes();
	}

	function nomes(){
		$this->rpg_nomes = [
			 $this->language->RPG_NO_SYSTEM
			,$this->language->RPG_DED
			,$this->language->RPG_DED4EDITION
			,$this->language->RPG_DED5EDITION
			,$this->language->RPG_DARKSUM
			,$this->language->RPG_FATE
			,$this->language->RPG_SEVAGE_WORLDS
			,$this->language->RPG_3DET
			,$this->language->RPG_DEAMON
			,$this->language->RPG_7MAR
			,$this->language->RPG_ABISMO
			,$this->language->RPG_ALCHEMIA
			,$this->language->RPG_ANIMES
			,$this->language->RPG_AVENTURAS_FANTASTICAS
			,$this->language->RPG_BLOOD_HONOR
			,$this->language->RPG_CHAMADO_DE_CTHULHU
			,$this->language->RPG_DUNGEON_WORLD
			,$this->language->RPG_DUNGEON_EVOLUTION
			,$this->language->RPG_GUERRA_DOS_DEUSES
			,$this->language->RPG_DUST_DEVILS
			,$this->language->RPG_ESTE_CORPO_MORTAL
			,$this->language->RPG_FIASCO
			,$this->language->RPG_FINAL_FANTASY
			,$this->language->RPG_FORGOTTEN_REALMS
			,$this->language->RPG_GUERRA_DOS_TRONOS
			,$this->language->RPG_GURPS
			,$this->language->RPG_MUTANTES_E_MALFEITORES
			,$this->language->RPG_SENHOR_DOS_ANEIS
			,$this->language->RPG_UM_ANEL
			,$this->language->RPG_OLD_DRAGON
			,$this->language->RPG_PATHFINDER
			,$this->language->RPG_REINOS_DE_FERRO
			,$this->language->RPG_QUEST
			,$this->language->RPG_SCION_HERO
			,$this->language->RPG_SHOTGUN_DIARIES
			,$this->language->RPG_SHADOWRUN
			,$this->language->RPG_SISTEMA_D20
			,$this->language->RPG_SPACE_DRAGON
			,$this->language->RPG_STAR_WARS
			,$this->language->RPG_STORYTELLER
			,$this->language->RPG_TAGMAR
			,$this->language->RPG_TERRA_DEVASTADA
			,$this->language->RPG_TORMENTA
			,$this->language->RPG_WORLD_WARCRAFT
			,$this->language->RPG_YGGDRASULL
			,$this->language->RPG_THE7SAGA
			,$this->language->RPG_ADVANCED_FIGHTING_FANTASY
			,$this->language->RPG_APOKALYPSE_WARS
			,$this->language->RPG_ARKANUN
			,$this->language->RPG_ARS_MAGICA
			,$this->language->RPG_BATTLE_KNIGHT
			,$this->language->RPG_THE_BLACK_COMPANY
			,$this->language->RPG_BLUE_ROSE
			,$this->language->RPG_BIE_FIGHT
			,$this->language->RPG_CABAL_ONLINE
			,$this->language->RPG_CALIOPE
			,$this->language->RPG_CASTELO_FALKENSTEIN
			,$this->language->RPG_CYBERPUNK_2020
			,$this->language->RPG_TORMENTA_3DT
			,$this->language->RPG_DELIRIA
			,$this->language->RPG_DRAGONMECH
			,$this->language->RPG_DSX
			,$this->language->RPG_DUNGEON_SIEGE_LEGENDS_OF_ARANNA
			,$this->language->RPG_DUNGEON_SIEGE_2
			,$this->language->RPG_DUNGEON_SIEGE_3
			,$this->language->RPG_DIABLO
			,$this->language->RPG_DOTA_2
			,$this->language->RPG_EARTHDAWN
			,$this->language->RPG_ELRIC
			,$this->language->RPG_EMPIRE_OF_THE_PETAL_THRONE
			,$this->language->RPG_EVERQUEST
			,$this->language->RPG_EXALTED
			,$this->language->RPG_FALLENSWORD
			,$this->language->RPG_HACKMASTER
			,$this->language->RPG_HARNMASTER_HARN
			,$this->language->RPG_HIGH_ADVENTURE_ROLE_PLAYING
			,$this->language->RPG_HAWKMOON
			,$this->language->RPG_HERO_WARS_HEROQUEST
			,$this->language->RPG_ISTARIA_CHRONICLES_OF_THE_GIFTED
			,$this->language->RPG_MIGHTY_BLADE
			,$this->language->RPG_MU_ONLINE
			,$this->language->RPG_O_DESAFIO_DOS_BANDEIRANTES
			,$this->language->RPG_PATHFINDER_ROLEPLAYING_GAME
			,$this->language->RPG_PERFECT_WORLD_PRISTON_TALE
			,$this->language->RPG_POTTERBRASIL
			,$this->language->RPG_RAGNAROK
			,$this->language->RPG_RIDDLE_OF_STEEL_PELA_DRIFTWOOD_PUBLISHING
			,$this->language->RPG_RIFTS_PELA_PALLADIUM_GAMES
			,$this->language->RPG_RMFRP
			,$this->language->RPG_RPGQUEST
			,$this->language->RPG_RUNEQUEST
			,$this->language->RPG_ROLEMASTER
			,$this->language->RPG_SHADOWRUN_FANTASIA_CYBERPUNK
			,$this->language->RPG_SILKROAD_ONLINE
			,$this->language->RPG_STORMBRINGER
			,$this->language->RPG_TALISLANTA
			,$this->language->RPG_THE_RIDDLE_OF_STEEL
			,$this->language->RPG_THE_SEVENTH_DRAGON
			,$this->language->RPG_TRIBE_8
			,$this->language->RPG_TUNNELS_AND_TROLLS
			,$this->language->RPG_TRAVIAN
			,$this->language->RPG_TALISMAN_ONLINE
			,$this->language->RPG_URBAN_RIVALS
			,$this->language->RPG_WARHAMMER_FANTASY_ROLEPLAY
			,$this->language->RPG_WEAPONS_OF_THE_GODS
			,$this->language->RPG_THE_WHEEL_OF_TIME_ROLEPLAYING_GAME
			,$this->language->RPG_W_Y_D_WITH_YOUR_DESTINY
			,$this->language->RPG_2300_AD
			,$this->language->RPG_ALTERNITY
			,$this->language->RPG_BATTLETECH
			,$this->language->RPG_BLUE_PLANET
			,$this->language->RPG_CONSPIRACY_X
			,$this->language->RPG_CYBERGENERATION
			,$this->language->RPG_CHRONO_TRIGGER
			,$this->language->RPG_D20_FUTURE
			,$this->language->RPG_DOCTOR_WHO_RPG
			,$this->language->RPG_DRAGONSTAR
			,$this->language->RPG_EX_MACHINA
			,$this->language->RPG_FADING_SUNS
			,$this->language->RPG_GAMMA_WORLD
			,$this->language->RPG_HI_BRAZIL
			,$this->language->RPG_INVASÃO
			,$this->language->RPG_MILLENIA
			,$this->language->RPG_NARUTO
			,$this->language->RPG_CAVALEIROS_DO_ZODÍACO
			,$this->language->RPG_DRAGON_BALL_Z
			,$this->language->RPG_OGAME
			,$this->language->RPG_SPACE_MASTER
			,$this->language->RPG_WYD_WITH_YOUR_DESTINY
			,$this->language->RPG_ALL_FLESH_MUST_BE_EATEN
			,$this->language->RPG_AQUELARRE
			,$this->language->RPG_BEYOND_THE_SUPERNATURAL
			,$this->language->RPG_BUREAU_13_STALKING_THE_NIGHT_FANTASTIC
			,$this->language->RPG_CHILL
			,$this->language->RPG_DEADLANDS_THE_WEIRD_WEST
			,$this->language->RPG_DEAD_INSIDE
			,$this->language->RPG_ERA_DO_CAOS
			,$this->language->RPG_LITTLE_FEARS
			,$this->language->RPG_KULT
			,$this->language->RPG_MY_LIFE_WITH_MASTER
			,$this->language->RPG_VAMPIRO_A_MÁSCARA
			,$this->language->RPG_LOBISOMEM_O_APOCALIPSE
			,$this->language->RPG_MAGO_A_ASCENSÃO
			,$this->language->RPG_WRAITH_THE_OBLIVION
			,$this->language->RPG_CHANGELING_O_SONHAR
			,$this->language->RPG_DEMÔNIO_A_QUEDA
			,$this->language->RPG_MÚMIA_A_RESSURREIÇÃO
			,$this->language->RPG_VAMPIROS_DO_ORIENTE
			,$this->language->RPG_HUNTER_THE_RECKONING
			,$this->language->RPG_VAMPIRO_O_RÉQUIEM
			,$this->language->RPG_LOBISOMEM_OS_DESTITUÍDOS
			,$this->language->RPG_MAGO_O_DESPERTAR
			,$this->language->RPG_PROMETHEAN_THE_CREATED
			,$this->language->RPG_CHANGELING_THE_LOST
			,$this->language->RPG_GEIST_THE_SIN_EATERS
			,$this->language->RPG_HUNTER_THE_VIGIL
			,$this->language->RPG_NEPHILIM
			,$this->language->RPG_NIGHTBANE
			,$this->language->RPG_OVER_THE_EDGE
			,$this->language->RPG_PARASITE_EVE
			,$this->language->RPG_PARASITE_EVE_2
			,$this->language->RPG_SEARCH_FOR_SALVATION
			,$this->language->RPG_TREVAS
			,$this->language->RPG_ANJOS_A_CIDADE_DE_PRATA
			,$this->language->RPG_DEMONIOS_A_DIVINA_COMÉDIA
			,$this->language->RPG_JYHAD_GUERRA_SANTA
			,$this->language->RPG_SPIRITUM_O_REINO_DOS_MORTOS
			,$this->language->RPG_VAMPIROS_MITOLOGICOS
			,$this->language->RPG_UNKNOWN_ARMIES
			,$this->language->RPG_THE_WHISPERING_VAULT
			,$this->language->RPG_WITCHCRAFT
			,$this->language->RPG_ENTRE_O_SUCESSO_E_A_LAMA
			,$this->language->RPG_DEFENSORES_DE_TÓQUIO
			,$this->language->RPG_MALDITOS_GOBLINS
			,$this->language->RPG_MULHERES_MACHONAS_ARMADAS_ATÉ_OS_DENTES
			,$this->language->RPG_PARANOIA_RPG
			,$this->language->RPG_TERRA_DE_OG
			,$this->language->RPG_TOON_RPG
			,$this->language->RPG_SILENT_HILL
			,$this->language->RPG_POKEMON_GAME
			,$this->language->RPG_WORLD_OF_WARCRAFT_PELA_WHITE_WOLF
			,$this->language->RPG_STAR_WARS_RPG
			,$this->language->RPG_STAR_TREK
		];
	}
}