<?php
$tag->div(['class'=>'row']);
    $tag->div(['class'=>'col-md-12']);
        $tag->h2();
            $tag->printer(UTILITIES_DICE);
        $tag->h2;
        $tag->printer('|');
        $tag->a(['href'=>'../index.php']);
            $tag->printer('Home');
        $tag->a;
        $tag->printer('|');
        $tag->a(['href'=>URL_BASE]);
            $tag->printer('helprpg.com.br');
        $tag->a;
        $tag->printer('|');
    $tag->div;
    $tag->hr();
$tag->div;